export { AdjectiveDeclensionTables } from './AdjectiveDeclensionTables';
export type { AdjectiveDeclensionTablesProps } from './AdjectiveDeclensionTables';
export { AdverbFormsTable } from './AdverbFormsTable';
export type { AdverbFormsTableProps } from './AdverbFormsTable';
export { CasesTable } from './CasesTable';
export { ConjugationTable } from './ConjugationTable';
export { NounDeclensionTable } from './NounDeclensionTable';
export type { NounDeclensionTableProps } from './NounDeclensionTable';
export { NounGrammarSection } from './NounGrammarSection';
export { PartOfSpeechBadge } from './PartOfSpeechBadge';
export type { PartOfSpeechBadgeProps } from './PartOfSpeechBadge';
export { TenseTabs } from './TenseTabs';
export { VerbConjugationGrid } from './VerbConjugationGrid';
export type { VerbConjugationGridProps } from './VerbConjugationGrid';
export { VerbGrammarSection } from './VerbGrammarSection';
