/**
 * Admin Exercises — Visual Regression Tests (TBR2-25-11)
 *
 * Chromatic snapshots for the admin Exercises page (ADMIN2-25).
 * Tests use mocked API responses so they run without a live backend.
 * Light-mode only — dark-mode coverage is parked (TBR2-25-13, default N/A).
 * Baseline PNGs are generated by the CI visual job against the preview deploy.
 *
 * Scenarios:
 *   1. Full page — default filters (Listening, all sources/types/levels/statuses)
 *   2. Toolbar zoom — all three filter rows visible and stable
 *   3. Stat-card grid zoom — four StatCards with mock counts
 *   4. Reading modality state — toolbar + rows after toggling to Reading
 */

import { test, expect } from '@chromatic-com/playwright';

import { navigateToAdminTab } from '../e2e/helpers/admin-helpers';
import {
  loginForVisualTest,
  takeSnapshot,
  waitForPageReady,
  VIEWPORTS,
} from './helpers/visual-helpers';

// ── Mock payloads ─────────────────────────────────────────────────────────────

const MOCK_EXERCISES = [
  {
    id: 'exr-vis-001',
    situation_title_el: 'Στο εστιατόριο',
    situation_title_en: 'At the restaurant',
    exercise_type: 'select_correct_answer',
    source_type: 'dialog',
    audio_level: 'A2',
    item_count: 5,
    status: 'approved',
    modality: 'listening',
  },
  {
    id: 'exr-vis-002',
    situation_title_el: 'Στην αγορά',
    situation_title_en: 'At the market',
    exercise_type: 'fill_gaps',
    source_type: 'description',
    audio_level: 'B1',
    item_count: 4,
    status: 'approved',
    modality: 'listening',
  },
  {
    id: 'exr-vis-003',
    situation_title_el: 'Στο σταθμό',
    situation_title_en: 'At the station',
    exercise_type: 'true_false',
    source_type: 'dialog',
    audio_level: 'A2',
    item_count: 3,
    status: 'pending',
    modality: 'listening',
  },
];

const MOCK_EXERCISES_READING = [
  {
    id: 'exr-vis-004',
    situation_title_el: 'Στο βιβλιοπωλείο',
    situation_title_en: 'At the bookshop',
    exercise_type: 'word_order',
    source_type: 'description',
    audio_level: 'B1',
    item_count: 6,
    status: 'approved',
    modality: 'reading',
  },
  {
    id: 'exr-vis-005',
    situation_title_el: 'Στο πάρκο',
    situation_title_en: 'In the park',
    exercise_type: 'select_correct_answer',
    source_type: 'picture',
    audio_level: 'A2',
    item_count: 4,
    status: 'draft',
    modality: 'reading',
  },
];

const MOCK_LIST = {
  items: MOCK_EXERCISES,
  total: 3,
  page: 1,
  page_size: 20,
  total_pages: 1,
};

const MOCK_LIST_READING = {
  items: MOCK_EXERCISES_READING,
  total: 2,
  page: 1,
  page_size: 20,
  total_pages: 1,
};

const MOCK_STATS = {
  total: 42,
  approved: 30,
  pending: 8,
  draft: 4,
  with_audio: 38,
  missing_audio: 4,
  distinct_types: 5,
};

// ── Helper: set up admin auth and mock exercises API ──────────────────────────

async function setupAdminWithMockedExercises(
  page: Parameters<typeof loginForVisualTest>[0],
  listPayload = MOCK_LIST
) {
  await loginForVisualTest(page);

  // Override localStorage role to admin
  await page.evaluate(() => {
    const authStorage = localStorage.getItem('auth-storage');
    if (authStorage) {
      const s = JSON.parse(authStorage);
      if (s?.state?.user) s.state.user.role = 'admin';
      localStorage.setItem('auth-storage', JSON.stringify(s));
    }
  });

  // Mock exercises endpoints — stats route must match before the general list check
  await page.route('**/api/v1/admin/exercises*', (route) => {
    const url = route.request().url();

    if (url.includes('/exercises/stats')) {
      route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(MOCK_STATS),
      });
      return;
    }

    route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify(listPayload),
    });
  });
}

// ── Tests ─────────────────────────────────────────────────────────────────────

test.describe('Admin Exercises — Visual (TBR2-25-11)', () => {
  // 1. Full page — default filters (Listening, all filters at default) ─────────

  test('exercises-full-page-default', async ({ page }, testInfo) => {
    await page.setViewportSize(VIEWPORTS.desktop);
    await setupAdminWithMockedExercises(page);

    await page.goto('/admin');
    await waitForPageReady(page, '[data-testid="admin-page"]');
    await navigateToAdminTab(page, 'exercises');

    // Wait for at least one exercise row chevron button to appear
    await page.getByTestId(/^admin-exercise-item-/).first().waitFor({ timeout: 10_000 });
    await page.waitForTimeout(300);

    await takeSnapshot(page, 'exercises-full-page-default', testInfo);
  });

  // 2. Toolbar zoom — all three filter rows ────────────────────────────────────

  test('exercises-toolbar-zoom', async ({ page }, testInfo) => {
    await page.setViewportSize(VIEWPORTS.desktop);
    await setupAdminWithMockedExercises(page);

    await page.goto('/admin');
    await waitForPageReady(page, '[data-testid="admin-page"]');
    await navigateToAdminTab(page, 'exercises');

    // Wait for all three toolbar rows to be visible
    await expect(page.getByTestId('exercises-toolbar-row-modality')).toBeVisible({
      timeout: 10_000,
    });
    await expect(page.getByTestId('exercises-toolbar-row-1')).toBeVisible();
    await expect(page.getByTestId('exercises-toolbar-row-2')).toBeVisible();
    await page.waitForTimeout(300);

    await takeSnapshot(page, 'exercises-toolbar-zoom', testInfo);
  });

  // 3. Stat-card grid zoom — four StatCards with mock counts ───────────────────

  test('exercises-stats-zoom', async ({ page }, testInfo) => {
    await page.setViewportSize(VIEWPORTS.desktop);
    await setupAdminWithMockedExercises(page);

    await page.goto('/admin');
    await waitForPageReady(page, '[data-testid="admin-page"]');
    await navigateToAdminTab(page, 'exercises');

    // Stats section is the first <section> child of admin-exercises-list
    const statsSection = page
      .getByTestId('admin-exercises-list')
      .locator('section')
      .first();
    await expect(statsSection).toBeVisible({ timeout: 10_000 });
    await page.waitForTimeout(300);

    await takeSnapshot(page, 'exercises-stats-zoom', testInfo);
  });

  // 4. Reading modality state ───────────────────────────────────────────────────

  test('exercises-reading-modality', async ({ page }, testInfo) => {
    await page.setViewportSize(VIEWPORTS.desktop);

    await loginForVisualTest(page);
    await page.evaluate(() => {
      const authStorage = localStorage.getItem('auth-storage');
      if (authStorage) {
        const s = JSON.parse(authStorage);
        if (s?.state?.user) s.state.user.role = 'admin';
        localStorage.setItem('auth-storage', JSON.stringify(s));
      }
    });

    // First list request returns listening exercises; after the modality toggle
    // the store resets and the next list request returns reading exercises.
    let listRequestCount = 0;
    await page.route('**/api/v1/admin/exercises*', (route) => {
      const url = route.request().url();

      if (url.includes('/exercises/stats')) {
        route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify(MOCK_STATS),
        });
        return;
      }

      listRequestCount++;
      const payload = listRequestCount <= 1 ? MOCK_LIST : MOCK_LIST_READING;
      route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(payload),
      });
    });

    await page.goto('/admin');
    await waitForPageReady(page, '[data-testid="admin-page"]');
    await navigateToAdminTab(page, 'exercises');

    // Wait for initial (Listening) list to render
    await page.getByTestId(/^admin-exercise-item-/).first().waitFor({ timeout: 10_000 });

    // Toggle to Reading — SegControl buttons have no testid; target by role + label text
    const modalityRow = page.getByTestId('exercises-toolbar-row-modality');
    await modalityRow.getByRole('button', { name: /reading/i }).click();

    // Wait for the Reading list to render (first reading exercise row)
    await page.getByTestId('admin-exercise-item-exr-vis-004').waitFor({ timeout: 10_000 });
    await page.waitForTimeout(300);

    await takeSnapshot(page, 'exercises-reading-modality', testInfo);
  });
});
