"""add_feedback_and_votes_tables

Revision ID: 75d4214a9e4f
Revises: d606f59197e7
Create Date: 2025-12-18 14:41:32.762362+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75d4214a9e4f"
down_revision: Union[str, Sequence[str], None] = "d606f59197e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "category",
            sa.Enum("FEATURE_REQUEST", "BUG_INCORRECT_DATA", name="feedbackcategory"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "UNDER_REVIEW",
                "PLANNED",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="feedbackstatus",
            ),
            nullable=False,
        ),
        sa.Column("vote_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feedback_category"), "feedback", ["category"], unique=False)
    op.create_index(op.f("ix_feedback_status"), "feedback", ["status"], unique=False)
    op.create_index(op.f("ix_feedback_user_id"), "feedback", ["user_id"], unique=False)
    op.create_index(op.f("ix_feedback_vote_count"), "feedback", ["vote_count"], unique=False)
    op.create_table(
        "feedback_votes",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("feedback_id", sa.Uuid(), nullable=False),
        sa.Column("vote_type", sa.Enum("UP", "DOWN", name="votetype"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.ForeignKeyConstraint(["feedback_id"], ["feedback.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "feedback_id", name="uq_user_feedback_vote"),
    )
    op.create_index(
        op.f("ix_feedback_votes_feedback_id"), "feedback_votes", ["feedback_id"], unique=False
    )
    op.create_index(op.f("ix_feedback_votes_user_id"), "feedback_votes", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_feedback_votes_user_id"), table_name="feedback_votes")
    op.drop_index(op.f("ix_feedback_votes_feedback_id"), table_name="feedback_votes")
    op.drop_table("feedback_votes")
    op.drop_index(op.f("ix_feedback_vote_count"), table_name="feedback")
    op.drop_index(op.f("ix_feedback_user_id"), table_name="feedback")
    op.drop_index(op.f("ix_feedback_status"), table_name="feedback")
    op.drop_index(op.f("ix_feedback_category"), table_name="feedback")
    op.drop_table("feedback")

    # Drop enum types
    sa.Enum(name="votetype").drop(op.get_bind())
    sa.Enum(name="feedbackstatus").drop(op.get_bind())
    sa.Enum(name="feedbackcategory").drop(op.get_bind())
    # ### end Alembic commands ###
