"""add_culture_exam_tables

Revision ID: b1dee5516e49
Revises: f34cfe534789
Create Date: 2025-12-23 15:17:40.718905+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1dee5516e49"
down_revision: Union[str, Sequence[str], None] = "f34cfe534789"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "culture_decks",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column(
            "name", sa.JSON(), nullable=False, comment="Multilingual deck name: {el, en, ru}"
        ),
        sa.Column(
            "description",
            sa.JSON(),
            nullable=False,
            comment="Multilingual deck description: {el, en, ru}",
        ),
        sa.Column(
            "icon",
            sa.String(length=50),
            nullable=False,
            comment="Icon identifier (e.g., emoji or icon name)",
        ),
        sa.Column(
            "color_accent",
            sa.String(length=7),
            nullable=False,
            comment="Hex color code for deck accent (e.g., #4CAF50)",
        ),
        sa.Column(
            "category",
            sa.String(length=50),
            nullable=False,
            comment="Category: history, geography, politics, culture, etc.",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "order_index", sa.Integer(), nullable=False, comment="Display order within category"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_culture_decks_category"), "culture_decks", ["category"], unique=False)
    op.create_index(
        op.f("ix_culture_decks_is_active"), "culture_decks", ["is_active"], unique=False
    )
    op.create_table(
        "culture_questions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("deck_id", sa.Uuid(), nullable=False),
        sa.Column(
            "question_text",
            sa.JSON(),
            nullable=False,
            comment="Multilingual question text: {el, en, ru}",
        ),
        sa.Column("option_a", sa.JSON(), nullable=False, comment="Option A: {el, en, ru}"),
        sa.Column("option_b", sa.JSON(), nullable=False, comment="Option B: {el, en, ru}"),
        sa.Column("option_c", sa.JSON(), nullable=False, comment="Option C: {el, en, ru}"),
        sa.Column("option_d", sa.JSON(), nullable=False, comment="Option D: {el, en, ru}"),
        sa.Column(
            "correct_option",
            sa.Integer(),
            nullable=False,
            comment="Correct option: 1=A, 2=B, 3=C, 4=D",
        ),
        sa.Column(
            "image_key",
            sa.String(length=500),
            nullable=True,
            comment="S3 key for question image (optional)",
        ),
        sa.Column("order_index", sa.Integer(), nullable=False, comment="Display order within deck"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.ForeignKeyConstraint(["deck_id"], ["culture_decks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_culture_questions_deck_id"), "culture_questions", ["deck_id"], unique=False
    )
    op.create_table(
        "culture_answer_history",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column(
            "language", sa.String(length=2), nullable=False, comment="Language used: el, en, ru"
        ),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column(
            "selected_option",
            sa.Integer(),
            nullable=False,
            comment="Selected option: 1=A, 2=B, 3=C, 4=D",
        ),
        sa.Column(
            "time_taken_seconds",
            sa.Integer(),
            nullable=False,
            comment="Time taken to answer in seconds",
        ),
        sa.Column(
            "deck_category",
            sa.String(length=50),
            nullable=False,
            comment="Deck category for streak queries",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.ForeignKeyConstraint(["question_id"], ["culture_questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_culture_answer_history_deck_category"),
        "culture_answer_history",
        ["deck_category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_culture_answer_history_is_correct"),
        "culture_answer_history",
        ["is_correct"],
        unique=False,
    )
    op.create_index(
        op.f("ix_culture_answer_history_language"),
        "culture_answer_history",
        ["language"],
        unique=False,
    )
    op.create_index(
        op.f("ix_culture_answer_history_question_id"),
        "culture_answer_history",
        ["question_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_culture_answer_history_user_id"),
        "culture_answer_history",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "culture_question_stats",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("easiness_factor", sa.Float(), nullable=False),
        sa.Column("interval", sa.Integer(), nullable=False),
        sa.Column("repetitions", sa.Integer(), nullable=False),
        sa.Column(
            "next_review_date", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=False
        ),
        sa.Column(
            "status",
            ENUM("NEW", "LEARNING", "REVIEW", "MASTERED", name="cardstatus", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.ForeignKeyConstraint(["question_id"], ["culture_questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "question_id", name="uq_user_culture_question"),
    )
    op.create_index(
        op.f("ix_culture_question_stats_next_review_date"),
        "culture_question_stats",
        ["next_review_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_culture_question_stats_question_id"),
        "culture_question_stats",
        ["question_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_culture_question_stats_status"), "culture_question_stats", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_culture_question_stats_user_id"),
        "culture_question_stats",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_culture_question_stats_user_id"), table_name="culture_question_stats")
    op.drop_index(op.f("ix_culture_question_stats_status"), table_name="culture_question_stats")
    op.drop_index(
        op.f("ix_culture_question_stats_question_id"), table_name="culture_question_stats"
    )
    op.drop_index(
        op.f("ix_culture_question_stats_next_review_date"), table_name="culture_question_stats"
    )
    op.drop_table("culture_question_stats")
    op.drop_index(op.f("ix_culture_answer_history_user_id"), table_name="culture_answer_history")
    op.drop_index(
        op.f("ix_culture_answer_history_question_id"), table_name="culture_answer_history"
    )
    op.drop_index(op.f("ix_culture_answer_history_language"), table_name="culture_answer_history")
    op.drop_index(op.f("ix_culture_answer_history_is_correct"), table_name="culture_answer_history")
    op.drop_index(
        op.f("ix_culture_answer_history_deck_category"), table_name="culture_answer_history"
    )
    op.drop_table("culture_answer_history")
    op.drop_index(op.f("ix_culture_questions_deck_id"), table_name="culture_questions")
    op.drop_table("culture_questions")
    op.drop_index(op.f("ix_culture_decks_is_active"), table_name="culture_decks")
    op.drop_index(op.f("ix_culture_decks_category"), table_name="culture_decks")
    op.drop_table("culture_decks")
    # ### end Alembic commands ###
