"""Add last_login_at and last_login_ip fields to User model

Revision ID: d606f59197e7
Revises: 8e2ce3fe8e88
Create Date: 2025-11-26 18:31:20.309050+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d606f59197e7"
down_revision: Union[str, Sequence[str], None] = "8e2ce3fe8e88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_card_statistics_user_due_cards"), table_name="card_statistics")
    op.add_column(
        "users",
        sa.Column(
            "last_login_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp of last successful login",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "last_login_ip",
            sa.String(length=45),
            nullable=True,
            comment="IP address of last successful login",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_login_ip")
    op.drop_column("users", "last_login_at")
    op.create_index(
        op.f("ix_card_statistics_user_due_cards"),
        "card_statistics",
        ["user_id", "next_review_date", "status"],
        unique=False,
    )
    # ### end Alembic commands ###
