"""add news_items table

Revision ID: 8eb622462a2f
Revises: c3c17642fed9
Create Date: 2026-01-25 19:25:25.760814+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8eb622462a2f"
down_revision: Union[str, Sequence[str], None] = "c3c17642fed9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "news_items",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column(
            "title_el", sa.String(length=500), nullable=False, comment="Article title in Greek"
        ),
        sa.Column(
            "description_el",
            sa.Text(),
            nullable=False,
            comment="Article description in Greek (max 1000 chars enforced at app level)",
        ),
        sa.Column(
            "title_en", sa.String(length=500), nullable=False, comment="Article title in English"
        ),
        sa.Column(
            "description_en",
            sa.Text(),
            nullable=False,
            comment="Article description in English (max 1000 chars enforced at app level)",
        ),
        sa.Column(
            "image_s3_key",
            sa.String(length=255),
            nullable=False,
            comment="S3 key for news item image (e.g., news/{uuid}.jpg)",
        ),
        sa.Column(
            "publication_date", sa.Date(), nullable=False, comment="Date the article was published"
        ),
        sa.Column(
            "original_article_url",
            sa.String(length=500),
            nullable=False,
            comment="URL of the original source article",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_news_items_original_article_url"),
        "news_items",
        ["original_article_url"],
        unique=True,
    )
    op.create_index(
        op.f("ix_news_items_publication_date"), "news_items", ["publication_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_news_items_publication_date"), table_name="news_items")
    op.drop_index(op.f("ix_news_items_original_article_url"), table_name="news_items")
    op.drop_table("news_items")
    # ### end Alembic commands ###
