"""create_card_records_table

Revision ID: 5e205ed1ffec
Revises: 9d753297038f
Create Date: 2026-02-06 06:48:03.341349+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e205ed1ffec"
down_revision: Union[str, Sequence[str], None] = "9d753297038f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "card_records",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("word_entry_id", sa.Uuid(), nullable=False),
        sa.Column("deck_id", sa.Uuid(), nullable=False),
        sa.Column(
            "card_type",
            postgresql.ENUM(
                "meaning_el_to_en",
                "meaning_en_to_el",
                "conjugation",
                "declension",
                "cloze",
                "sentence_translation",
                name="cardtype",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("tier", sa.Integer(), nullable=True),
        sa.Column("front_content", sa.JSON(), nullable=False),
        sa.Column("back_content", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.ForeignKeyConstraint(["deck_id"], ["decks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["word_entry_id"], ["word_entries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "word_entry_id", "card_type", "tier", name="uq_card_record_entry_type_tier"
        ),
    )
    op.create_index("ix_card_records_card_type", "card_records", ["card_type"], unique=False)
    op.create_index(
        "ix_card_records_deck_active", "card_records", ["deck_id", "is_active"], unique=False
    )
    op.create_index("ix_card_records_deck_id", "card_records", ["deck_id"], unique=False)
    op.create_index(
        "ix_card_records_deck_type", "card_records", ["deck_id", "card_type"], unique=False
    )
    op.create_index("ix_card_records_is_active", "card_records", ["is_active"], unique=False)
    op.create_index("ix_card_records_tier", "card_records", ["tier"], unique=False)
    op.create_index(
        "ix_card_records_word_entry_id", "card_records", ["word_entry_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_card_records_word_entry_id", table_name="card_records")
    op.drop_index("ix_card_records_tier", table_name="card_records")
    op.drop_index("ix_card_records_is_active", table_name="card_records")
    op.drop_index("ix_card_records_deck_type", table_name="card_records")
    op.drop_index("ix_card_records_deck_id", table_name="card_records")
    op.drop_index("ix_card_records_deck_active", table_name="card_records")
    op.drop_index("ix_card_records_card_type", table_name="card_records")
    op.drop_table("card_records")
    # ### end Alembic commands ###
