"""add_card_search_array_fields

Revision ID: 014f35839083
Revises: a90d6c7deeb3
Create Date: 2026-01-29 13:03:49.627995+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "014f35839083"
down_revision: Union[str, Sequence[str], None] = "a90d6c7deeb3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cards",
        sa.Column(
            "searchable_forms",
            postgresql.ARRAY(sa.String()),
            nullable=True,
            comment="All inflected forms for exact matching",
        ),
    )
    op.add_column(
        "cards",
        sa.Column(
            "searchable_forms_normalized",
            postgresql.ARRAY(sa.String()),
            nullable=True,
            comment="Accent-stripped forms for fuzzy matching",
        ),
    )
    # ### end Alembic commands ###

    # Create GIN indexes for efficient array search
    op.create_index(
        "ix_cards_searchable_forms", "cards", ["searchable_forms"], postgresql_using="gin"
    )
    op.create_index(
        "ix_cards_searchable_forms_normalized",
        "cards",
        ["searchable_forms_normalized"],
        postgresql_using="gin",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Drop GIN indexes first
    op.drop_index("ix_cards_searchable_forms_normalized", table_name="cards")
    op.drop_index("ix_cards_searchable_forms", table_name="cards")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cards", "searchable_forms_normalized")
    op.drop_column("cards", "searchable_forms")
    # ### end Alembic commands ###
