"""add_source_fetch_history_table

Revision ID: 910421a50d22
Revises: 29695fa3f73f
Create Date: 2026-01-22 16:05:43.998081+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "910421a50d22"
down_revision: Union[str, Sequence[str], None] = "29695fa3f73f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_fetch_history",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), nullable=False, comment="'success' or 'error'"),
        sa.Column(
            "html_content", sa.Text(), nullable=True, comment="Raw HTML content (null if error)"
        ),
        sa.Column("html_size_bytes", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column(
            "trigger_type", sa.String(length=20), nullable=False, comment="'manual' or 'scheduled'"
        ),
        sa.Column(
            "final_url", sa.String(length=500), nullable=True, comment="Final URL after redirects"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.ForeignKeyConstraint(["source_id"], ["news_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_fetch_history_source_fetched",
        "source_fetch_history",
        ["source_id", sa.literal_column("fetched_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_fetch_history_source_id"),
        "source_fetch_history",
        ["source_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_source_fetch_history_source_id"), table_name="source_fetch_history")
    op.drop_index("idx_fetch_history_source_fetched", table_name="source_fetch_history")
    op.drop_table("source_fetch_history")
    # ### end Alembic commands ###
