"""add announcement_campaigns table and admin_announcement enum

Revision ID: e9377d765b32
Revises: 591a7e0356d9
Create Date: 2026-01-27 11:30:20.457342+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9377d765b32"
down_revision: Union[str, Sequence[str], None] = "591a7e0356d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new enum value for admin announcements
    # Note: PostgreSQL enum values cannot be removed in downgrade, only added
    op.execute("ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'admin_announcement'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "announcement_campaigns",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column(
            "title",
            sa.String(length=100),
            nullable=False,
            comment="Announcement title (max 100 chars)",
        ),
        sa.Column("message", sa.Text(), nullable=False, comment="Announcement message content"),
        sa.Column(
            "link_url",
            sa.String(length=500),
            nullable=True,
            comment="Optional URL for users to click",
        ),
        sa.Column(
            "created_by",
            sa.Uuid(),
            nullable=False,
            comment="Admin user who created the announcement",
        ),
        sa.Column(
            "total_recipients",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="Total number of users who received the announcement",
        ),
        sa.Column(
            "read_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="Number of users who read the announcement",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_announcement_campaigns_created_by"),
        "announcement_campaigns",
        ["created_by"],
        unique=False,
    )
    # Add index for sorting by creation date (newest first)
    op.create_index(
        "ix_announcement_campaigns_created_at",
        "announcement_campaigns",
        [sa.text("created_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_announcement_campaigns_created_at", table_name="announcement_campaigns")
    op.drop_index(op.f("ix_announcement_campaigns_created_by"), table_name="announcement_campaigns")
    op.drop_table("announcement_campaigns")
    # Note: PostgreSQL enum values cannot be removed, so we don't try to remove
    # 'admin_announcement' from notificationtype enum
    # ### end Alembic commands ###
