"""remove_difficulty_and_order_index_from_cards

Revision ID: 14c4b1b4a7a8
Revises: 5208d6f4ad95
Create Date: 2026-01-29 11:29:10.325683+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14c4b1b4a7a8"
down_revision: Union[str, Sequence[str], None] = "5208d6f4ad95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cards_difficulty"), table_name="cards")
    op.drop_column("cards", "difficulty")
    op.drop_column("cards", "order_index")
    # Drop the enum type
    op.execute("DROP TYPE IF EXISTS carddifficulty")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate the enum type
    carddifficulty_enum = postgresql.ENUM(
        "EASY", "MEDIUM", "HARD", name="carddifficulty", create_type=False
    )
    carddifficulty_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "cards",
        sa.Column(
            "order_index", sa.INTEGER(), autoincrement=False, nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "cards",
        sa.Column(
            "difficulty",
            carddifficulty_enum,
            autoincrement=False,
            nullable=False,
            server_default="MEDIUM",
        ),
    )
    op.create_index(op.f("ix_cards_difficulty"), "cards", ["difficulty"], unique=False)
    # Remove server defaults after columns are added
    op.alter_column("cards", "order_index", server_default=None)
    op.alter_column("cards", "difficulty", server_default=None)
    # ### end Alembic commands ###
