"""lexgen_04_cefr_lemma

Revision ID: 844af57c6ca2
Revises: 5e8cc90e5bca
Create Date: 2026-06-20 08:00:46.327343+00:00

Hand-written (NOT autogenerated): the ``reference`` schema is deliberately
excluded from Alembic autogenerate in ``alembic/env.py`` (``include_object`` /
``include_name`` both filter it out) so reference-schema migrations are written
by hand — same convention as greek_lexicon / translations / wiktionary_morphology.
``alembic --autogenerate`` produces an empty body for reference tables by design;
``alembic check`` is therefore blind to reference drift, and the real backstop is
the round-trip migration test (tests/integration/migrations/test_lexgen_04_cefr_lemma.py).

Creates two tables in the ``reference`` schema (LEXGEN-04):
  - reference.cefr_lemma        — CEFR introduction-level set, keyed by lemma
  - reference.cefr_lemma_review — quarantine for candidates that failed
                                  normalization or attestation

The cefr_lemma backstop is a UNIQUE index on ``(lemma)`` ALONE (F1 / D-UNIQUE-LEMMA)
so each lemma resolves to exactly one canonical introduction level; ``level`` carries
a separate non-unique index for 'all lemmas <= target level' gate queries.
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "844af57c6ca2"
down_revision: Union[str, Sequence[str], None] = "5e8cc90e5bca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create reference.cefr_lemma + reference.cefr_lemma_review and their indexes."""
    op.create_table(
        "cefr_lemma",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Auto-incrementing primary key",
        ),
        sa.Column(
            "lemma",
            sa.Text(),
            nullable=False,
            comment="Normalized Greek lemma (dictionary form) — the set-membership key",
        ),
        sa.Column(
            "level",
            sa.Text(),
            nullable=False,
            comment="CEFR introduction level: A1 | A2 | B1 (extensible; v1 stores these three)",
        ),
        sa.Column(
            "source",
            sa.Text(),
            nullable=False,
            comment="Provenance per row (keg_glossary | deck_export | frequency_bin | closed_class)",
        ),
        sa.Column(
            "closed_class",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="True for closed-class function words seeded from the whitelist",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
            comment="Row creation timestamp",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="reference",
    )
    # F1 / D-UNIQUE-LEMMA: UNIQUE on (lemma) ALONE — NOT (lemma, level) — so each
    # lemma resolves to exactly one canonical introduction level.
    op.create_index(
        "uq_cefr_lemma_lemma",
        "cefr_lemma",
        ["lemma"],
        unique=True,
        schema="reference",
    )
    # Separate non-unique index for 'all lemmas <= target level' gate queries.
    op.create_index(
        "ix_cefr_lemma_level",
        "cefr_lemma",
        ["level"],
        unique=False,
        schema="reference",
    )

    op.create_table(
        "cefr_lemma_review",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Auto-incrementing primary key",
        ),
        sa.Column(
            "raw_lemma",
            sa.Text(),
            nullable=False,
            comment="The pre-normalization candidate lemma as supplied by the source",
        ),
        sa.Column(
            "normalized_lemma",
            sa.Text(),
            nullable=True,
            comment="Normalized form (present if normalization succeeded but attestation failed)",
        ),
        sa.Column(
            "level",
            sa.Text(),
            nullable=True,
            comment="CEFR level the candidate would have been introduced at",
        ),
        sa.Column(
            "source",
            sa.Text(),
            nullable=True,
            comment="Provenance of the candidate (same vocabulary as cefr_lemma.source)",
        ),
        sa.Column(
            "reason",
            sa.Text(),
            nullable=False,
            comment="Why the candidate was quarantined (e.g. normalization_failed | not_attested)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
            comment="Row creation timestamp",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="reference",
    )


def downgrade() -> None:
    """Drop both tables and their indexes (reverse order)."""
    op.drop_table("cefr_lemma_review", schema="reference")
    op.drop_index("ix_cefr_lemma_level", table_name="cefr_lemma", schema="reference")
    op.drop_index("uq_cefr_lemma_lemma", table_name="cefr_lemma", schema="reference")
    op.drop_table("cefr_lemma", schema="reference")
