"""add_column_comments

Revision ID: b433bd53507e
Revises: 770a1b39d506
Create Date: 2026-02-04 07:22:43.309178+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b433bd53507e"
down_revision: Union[str, Sequence[str], None] = "770a1b39d506"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "card_error_reports",
        "card_type",
        existing_type=postgresql.ENUM("VOCABULARY", "CULTURE", name="carderrorcardtype"),
        comment="Type of card: vocabulary (Card) or culture (CultureQuestion)",
        existing_nullable=False,
    )
    op.alter_column(
        "card_error_reports",
        "card_id",
        existing_type=sa.UUID(),
        comment="UUID of the Card or CultureQuestion being reported",
        existing_nullable=False,
    )
    op.alter_column(
        "card_error_reports",
        "description",
        existing_type=sa.TEXT(),
        comment="User's description of the error (max 1000 chars enforced at API level)",
        existing_nullable=False,
    )
    op.alter_column(
        "card_error_reports",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING", "REVIEWED", "FIXED", "DISMISSED", name="carderrorstatus"
        ),
        comment="Report status: pending, reviewed, fixed, dismissed",
        existing_nullable=False,
        existing_server_default=sa.text("'PENDING'::carderrorstatus"),
    )
    op.alter_column(
        "card_error_reports",
        "admin_notes",
        existing_type=sa.TEXT(),
        comment="Internal admin notes about the resolution",
        existing_nullable=True,
    )
    op.alter_column(
        "card_error_reports",
        "resolved_by",
        existing_type=sa.UUID(),
        comment="Admin user who resolved the report",
        existing_nullable=True,
    )
    op.alter_column(
        "user_settings",
        "preferred_language",
        existing_type=sa.VARCHAR(length=10),
        comment="ISO 639-1 language code (e.g., 'en', 'ru')",
        existing_comment="ISO 639-1 language code (e.g., 'en', 'el')",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_settings",
        "preferred_language",
        existing_type=sa.VARCHAR(length=10),
        comment="ISO 639-1 language code (e.g., 'en', 'el')",
        existing_comment="ISO 639-1 language code (e.g., 'en', 'ru')",
        existing_nullable=True,
    )
    op.alter_column(
        "card_error_reports",
        "resolved_by",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="Admin user who resolved the report",
        existing_nullable=True,
    )
    op.alter_column(
        "card_error_reports",
        "admin_notes",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Internal admin notes about the resolution",
        existing_nullable=True,
    )
    op.alter_column(
        "card_error_reports",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING", "REVIEWED", "FIXED", "DISMISSED", name="carderrorstatus"
        ),
        comment=None,
        existing_comment="Report status: pending, reviewed, fixed, dismissed",
        existing_nullable=False,
        existing_server_default=sa.text("'PENDING'::carderrorstatus"),
    )
    op.alter_column(
        "card_error_reports",
        "description",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="User's description of the error (max 1000 chars enforced at API level)",
        existing_nullable=False,
    )
    op.alter_column(
        "card_error_reports",
        "card_id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="UUID of the Card or CultureQuestion being reported",
        existing_nullable=False,
    )
    op.alter_column(
        "card_error_reports",
        "card_type",
        existing_type=postgresql.ENUM("VOCABULARY", "CULTURE", name="carderrorcardtype"),
        comment=None,
        existing_comment="Type of card: vocabulary (Card) or culture (CultureQuestion)",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
