"""add_changelog_entries

Revision ID: 92fbcfbc75fd
Revises: f1d6e4ac4839
Create Date: 2026-01-27 16:24:25.442452+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92fbcfbc75fd"
down_revision: Union[str, Sequence[str], None] = "f1d6e4ac4839"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "changelog_entries",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("title_en", sa.String(length=500), nullable=False, comment="Title in English"),
        sa.Column(
            "content_en",
            sa.Text(),
            nullable=False,
            comment="Content in English (supports bold/italic markdown)",
        ),
        sa.Column("title_el", sa.String(length=500), nullable=False, comment="Title in Greek"),
        sa.Column(
            "content_el",
            sa.Text(),
            nullable=False,
            comment="Content in Greek (supports bold/italic markdown)",
        ),
        sa.Column("title_ru", sa.String(length=500), nullable=False, comment="Title in Russian"),
        sa.Column(
            "content_ru",
            sa.Text(),
            nullable=False,
            comment="Content in Russian (supports bold/italic markdown)",
        ),
        sa.Column(
            "tag",
            sa.Enum("NEW_FEATURE", "BUG_FIX", "ANNOUNCEMENT", name="changelogtag"),
            nullable=False,
            comment="Entry type: new_feature, bug_fix, announcement",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_changelog_entries_created_at_desc",
        "changelog_entries",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(op.f("ix_changelog_entries_tag"), "changelog_entries", ["tag"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_changelog_entries_tag"), table_name="changelog_entries")
    op.drop_index("ix_changelog_entries_created_at_desc", table_name="changelog_entries")
    op.drop_table("changelog_entries")
    # Drop the enum type
    sa.Enum(name="changelogtag").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
