"""add translation_ru_plural to word_entries

Revision ID: d0bf063e5db5
Revises: d8c84a489918
Create Date: 2026-02-09 17:45:08.189932+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0bf063e5db5"
down_revision: Union[str, Sequence[str], None] = "d8c84a489918"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "word_entries",
        sa.Column(
            "translation_ru_plural",
            sa.String(length=500),
            nullable=True,
            comment="Russian plural translation(s), comma-separated for multiple meanings",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("word_entries", "translation_ru_plural")
    # ### end Alembic commands ###
