"""add news_item_id and audio_s3_key to culture_questions

Revision ID: aed6e9269356
Revises: 9822ff96fec6
Create Date: 2026-02-13 19:39:09.381178+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aed6e9269356"
down_revision: Union[str, Sequence[str], None] = "9822ff96fec6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "culture_questions",
        sa.Column(
            "news_item_id",
            sa.Uuid(),
            nullable=True,
            comment="FK to news_items.id for questions derived from news articles",
        ),
    )
    op.add_column(
        "culture_questions",
        sa.Column(
            "audio_s3_key",
            sa.String(length=500),
            nullable=True,
            comment="S3 key for TTS-generated audio file (e.g., culture/audio/{uuid}.mp3)",
        ),
    )

    # Backfill news_item_id from original_article_url matches
    op.execute(
        """
        UPDATE culture_questions
        SET news_item_id = news_items.id
        FROM news_items
        WHERE culture_questions.original_article_url = news_items.original_article_url
          AND culture_questions.news_item_id IS NULL
          AND news_items.original_article_url IS NOT NULL
        """
    )

    op.create_index(
        op.f("ix_culture_questions_news_item_id"),
        "culture_questions",
        ["news_item_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_culture_questions_news_item_id_news_items",
        "culture_questions",
        "news_items",
        ["news_item_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("culture_questions", "audio_s3_key")
    op.drop_index(op.f("ix_culture_questions_news_item_id"), table_name="culture_questions")
    op.drop_constraint(
        "fk_culture_questions_news_item_id_news_items", "culture_questions", type_="foreignkey"
    )
    op.drop_column("culture_questions", "news_item_id")
    # ### end Alembic commands ###
