"""add_is_premium_to_decks

Revision ID: 0243cb807282
Revises: f9230d7fa07a
Create Date: 2026-01-15 21:03:56.564237+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0243cb807282"
down_revision: Union[str, Sequence[str], None] = "f9230d7fa07a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "culture_decks",
        sa.Column(
            "is_premium",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
            comment="Premium decks require a subscription to access",
        ),
    )
    op.create_index(
        op.f("ix_culture_decks_is_premium"), "culture_decks", ["is_premium"], unique=False
    )
    op.add_column(
        "decks",
        sa.Column(
            "is_premium",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
            comment="Premium decks require a subscription to access",
        ),
    )
    op.create_index(op.f("ix_decks_is_premium"), "decks", ["is_premium"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_decks_is_premium"), table_name="decks")
    op.drop_column("decks", "is_premium")
    op.drop_index(op.f("ix_culture_decks_is_premium"), table_name="culture_decks")
    op.drop_column("culture_decks", "is_premium")
    # ### end Alembic commands ###
