"""add mock exam tables

Revision ID: 7b7663a8d448
Revises: 2cb115953b2a
Create Date: 2026-01-17 21:50:33.304356+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b7663a8d448"
down_revision: Union[str, Sequence[str], None] = "2cb115953b2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mock_exam_sessions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("total_questions", sa.Integer(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("time_taken_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "COMPLETED", "ABANDONED", name="mockexamstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mock_exam_sessions_status"), "mock_exam_sessions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_mock_exam_sessions_user_id"), "mock_exam_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "mock_exam_answers",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("selected_option", sa.Integer(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("time_taken_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "answered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.ForeignKeyConstraint(["question_id"], ["culture_questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["mock_exam_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mock_exam_answers_is_correct"), "mock_exam_answers", ["is_correct"], unique=False
    )
    op.create_index(
        op.f("ix_mock_exam_answers_question_id"), "mock_exam_answers", ["question_id"], unique=False
    )
    op.create_index(
        op.f("ix_mock_exam_answers_session_id"), "mock_exam_answers", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mock_exam_answers_session_id"), table_name="mock_exam_answers")
    op.drop_index(op.f("ix_mock_exam_answers_question_id"), table_name="mock_exam_answers")
    op.drop_index(op.f("ix_mock_exam_answers_is_correct"), table_name="mock_exam_answers")
    op.drop_table("mock_exam_answers")
    op.drop_index(op.f("ix_mock_exam_sessions_user_id"), table_name="mock_exam_sessions")
    op.drop_index(op.f("ix_mock_exam_sessions_status"), table_name="mock_exam_sessions")
    op.drop_table("mock_exam_sessions")
    # ### end Alembic commands ###
