"""add audio columns to news_items

Revision ID: 9822ff96fec6
Revises: c24dff20b712
Create Date: 2026-02-13 05:02:43.700225+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9822ff96fec6"
down_revision: Union[str, Sequence[str], None] = "c24dff20b712"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "news_items",
        sa.Column(
            "audio_s3_key",
            sa.String(length=500),
            nullable=True,
            comment="S3 key for TTS-generated audio file (e.g., news/audio/{uuid}.mp3)",
        ),
    )
    op.add_column(
        "news_items",
        sa.Column(
            "audio_generated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when audio was generated via TTS",
        ),
    )
    op.add_column(
        "news_items",
        sa.Column(
            "audio_file_size_bytes",
            sa.Integer(),
            nullable=True,
            comment="Size of audio file in bytes",
        ),
    )
    op.add_column(
        "news_items",
        sa.Column(
            "audio_duration_seconds",
            sa.Float(),
            nullable=True,
            comment="Duration of audio in seconds",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news_items", "audio_duration_seconds")
    op.drop_column("news_items", "audio_file_size_bytes")
    op.drop_column("news_items", "audio_generated_at")
    op.drop_column("news_items", "audio_s3_key")
    # ### end Alembic commands ###
