"""Add theme to user_settings

Revision ID: f9230d7fa07a
Revises: b0161f8a
Create Date: 2026-01-13 16:26:14.335906+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9230d7fa07a"
down_revision: Union[str, Sequence[str], None] = "b0161f8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_settings",
        sa.Column(
            "theme",
            sa.String(length=10),
            nullable=True,
            comment="User's preferred theme: 'light' or 'dark'",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_settings", "theme")
    # ### end Alembic commands ###
