"""add dialog progress tables

Revision ID: 8b5463ae5571
Revises: 79294725f353
Create Date: 2026-03-12 07:04:39.673936+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b5463ae5571"
down_revision: Union[str, Sequence[str], None] = "79294725f353"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dialog_progress",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("dialog_id", sa.Uuid(), nullable=False),
        sa.Column(
            "exercises_completed", sa.SmallInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("all_completed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("first_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.ForeignKeyConstraint(["dialog_id"], ["listening_dialogs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "dialog_id", name="uq_dialog_progress_user_dialog"),
    )
    op.create_index(
        op.f("ix_dialog_progress_user_id"), "dialog_progress", ["user_id"], unique=False
    )
    op.create_table(
        "dialog_exercise_attempts",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("exercise_id", sa.Uuid(), nullable=False),
        sa.Column("score", sa.SmallInteger(), nullable=False),
        sa.Column("max_score", sa.SmallInteger(), nullable=False),
        sa.Column("time_taken_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["exercise_id"], ["dialog_exercises.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_dialog_exercise_attempts_user_exercise",
        "dialog_exercise_attempts",
        ["user_id", "exercise_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dialog_exercise_attempts_user_id"),
        "dialog_exercise_attempts",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_dialog_exercise_attempts_user_id"), table_name="dialog_exercise_attempts"
    )
    op.drop_index(
        "ix_dialog_exercise_attempts_user_exercise", table_name="dialog_exercise_attempts"
    )
    op.drop_table("dialog_exercise_attempts")
    op.drop_index(op.f("ix_dialog_progress_user_id"), table_name="dialog_progress")
    op.drop_table("dialog_progress")
    # ### end Alembic commands ###
