"""add translation_en_plural to word_entries

Revision ID: cb083902fa3c
Revises: 456913a8989a
Create Date: 2026-02-08 21:27:00.091064+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb083902fa3c"
down_revision: Union[str, Sequence[str], None] = "456913a8989a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "word_entries",
        sa.Column(
            "translation_en_plural",
            sa.String(length=500),
            nullable=True,
            comment="English plural translation(s), comma-separated for multiple meanings",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("word_entries", "translation_en_plural")
    # ### end Alembic commands ###
