"""dbkg_01_add_cover_image_s3_key

Revision ID: 2a21cd907b19
Revises: d2e3f4a5b6c7
Create Date: 2026-03-16 18:06:35.633047+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a21cd907b19"
down_revision: Union[str, Sequence[str], None] = "d2e3f4a5b6c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "decks",
        sa.Column(
            "cover_image_s3_key",
            sa.String(length=500),
            nullable=True,
            comment="S3 object key for deck cover image",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("decks", "cover_image_s3_key")
    # ### end Alembic commands ###
