"""add owner_id to decks table

Revision ID: 2cb115953b2a
Revises: 0243cb807282
Create Date: 2026-01-16 16:23:58.764975+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2cb115953b2a"
down_revision: Union[str, Sequence[str], None] = "0243cb807282"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "decks",
        sa.Column(
            "owner_id",
            sa.Uuid(),
            nullable=True,
            comment="Owner user ID (NULL for system decks, UUID for user-created decks)",
        ),
    )
    op.create_index(op.f("ix_decks_owner_id"), "decks", ["owner_id"], unique=False)
    op.create_foreign_key(
        "fk_decks_owner_id_users",
        "decks",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_decks_owner_id_users", "decks", type_="foreignkey")
    op.drop_index(op.f("ix_decks_owner_id"), table_name="decks")
    op.drop_column("decks", "owner_id")
    # ### end Alembic commands ###
