"""add webhook_events table

Revision ID: 49e74532bcd3
Revises: 1fb3903d043e
Create Date: 2026-02-18 12:33:55.729075+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49e74532bcd3"
down_revision: Union[str, Sequence[str], None] = "1fb3903d043e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhook_events",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column(
            "event_id",
            sa.String(length=255),
            nullable=False,
            comment="Stripe event ID (evt_xxx) - unique for idempotency",
        ),
        sa.Column(
            "event_type",
            sa.String(length=255),
            nullable=False,
            comment="Stripe event type (e.g., customer.subscription.updated)",
        ),
        sa.Column(
            "raw_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Complete Stripe webhook event payload",
        ),
        sa.Column(
            "processing_status",
            sa.Enum("PROCESSING", "COMPLETED", "FAILED", name="webhookprocessingstatus"),
            server_default=sa.text("'PROCESSING'"),
            nullable=False,
            comment="Webhook processing status: processing, completed, failed",
        ),
        sa.Column(
            "error_message", sa.Text(), nullable=True, comment="Error message if processing failed"
        ),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When webhook processing completed (success or failure)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_webhook_events_event_id"), "webhook_events", ["event_id"], unique=True)
    op.create_index(
        op.f("ix_webhook_events_event_type"), "webhook_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_events_processing_status"),
        "webhook_events",
        ["processing_status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_webhook_events_processing_status"), table_name="webhook_events")
    op.drop_index(op.f("ix_webhook_events_event_type"), table_name="webhook_events")
    op.drop_index(op.f("ix_webhook_events_event_id"), table_name="webhook_events")
    op.drop_table("webhook_events")
    postgresql.ENUM(
        "PROCESSING",
        "COMPLETED",
        "FAILED",
        name="webhookprocessingstatus",
    ).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
