"""lexgen_05_frequency_rank

Revision ID: 6b8e5cdc102f
Revises: 844af57c6ca2
Create Date: 2026-06-20 18:37:28.299321+00:00

Hand-written (NOT autogenerated): the ``reference`` schema is deliberately
excluded from Alembic autogenerate in ``alembic/env.py`` (``include_object`` /
``include_name`` both filter it out) so reference-schema migrations are written
by hand — same convention as cefr_lemma / greek_lexicon / wiktionary_morphology.
``alembic --autogenerate`` produces an empty body for reference tables by design;
``alembic check`` is therefore blind to reference drift, and the real backstop is
the round-trip migration test (tests/integration/migrations/test_lexgen_05_frequency_rank.py).

Creates one table in the ``reference`` schema (LEXGEN-05):
  - reference.frequency_rank — static word-frequency list keyed by Greek lemma

The DB backstop is a UNIQUE index on ``(lemma)`` ALONE (D-UNIQUE-LEMMA):
a ``(lemma, rank)`` unique key would wrongly permit two contradictory frequency
ranks for the same lemma (e.g. from conflicting sources), corrupting the
single-source-of-truth invariant.  The ``rank`` index is separate and non-unique
so rank-ordered lookups ('all lemmas with rank <= N') remain efficient.
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b8e5cdc102f"
down_revision: Union[str, Sequence[str], None] = "844af57c6ca2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create reference.frequency_rank and its indexes."""
    op.create_table(
        "frequency_rank",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Auto-incrementing primary key",
        ),
        sa.Column(
            "lemma",
            sa.Text(),
            nullable=False,
            comment="Normalized Greek lemma — the join key (lowercase + NFC, matches cefr_lemma)",
        ),
        sa.Column(
            "rank",
            sa.Integer(),
            nullable=False,
            comment="Dense rank, 1 = most frequent",
        ),
        sa.Column(
            "source",
            sa.Text(),
            nullable=False,
            comment="Provenance, e.g. 'wordfreq'",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
            comment="Row creation timestamp",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="reference",
    )
    # D-UNIQUE-LEMMA: UNIQUE on (lemma) ALONE — NOT (lemma, rank) — so each
    # lemma resolves to exactly one canonical frequency rank.
    op.create_index(
        "uq_frequency_rank_lemma",
        "frequency_rank",
        ["lemma"],
        unique=True,
        schema="reference",
    )
    # Separate non-unique index for rank-ordered range lookups.
    op.create_index(
        "ix_frequency_rank_rank",
        "frequency_rank",
        ["rank"],
        unique=False,
        schema="reference",
    )


def downgrade() -> None:
    """Drop reference.frequency_rank and its indexes (reverse order)."""
    op.drop_index("ix_frequency_rank_rank", table_name="frequency_rank", schema="reference")
    op.drop_index("uq_frequency_rank_lemma", table_name="frequency_rank", schema="reference")
    op.drop_table("frequency_rank", schema="reference")
