"""add a2 columns to news items

Revision ID: bbfda52f7a72
Revises: 6011531b4324
Create Date: 2026-03-01 08:37:51.149622+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bbfda52f7a72"
down_revision: Union[str, Sequence[str], None] = "6011531b4324"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "news_items",
        sa.Column(
            "title_el_a2",
            sa.String(length=500),
            nullable=True,
            comment="Simplified A2-level article title in Greek",
        ),
    )
    op.add_column(
        "news_items",
        sa.Column(
            "description_el_a2",
            sa.Text(),
            nullable=True,
            comment="Simplified A2-level article description in Greek",
        ),
    )
    op.add_column(
        "news_items",
        sa.Column(
            "audio_a2_s3_key",
            sa.String(length=500),
            nullable=True,
            comment="S3 key for A2-level TTS audio file",
        ),
    )
    op.add_column(
        "news_items",
        sa.Column(
            "audio_a2_generated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when A2 audio was generated via TTS",
        ),
    )
    op.add_column(
        "news_items",
        sa.Column(
            "audio_a2_duration_seconds",
            sa.Float(),
            nullable=True,
            comment="Duration of A2 audio file in seconds",
        ),
    )
    op.add_column(
        "news_items",
        sa.Column(
            "audio_a2_file_size_bytes",
            sa.Integer(),
            nullable=True,
            comment="Size of A2 audio file in bytes",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news_items", "audio_a2_file_size_bytes")
    op.drop_column("news_items", "audio_a2_duration_seconds")
    op.drop_column("news_items", "audio_a2_generated_at")
    op.drop_column("news_items", "audio_a2_s3_key")
    op.drop_column("news_items", "description_el_a2")
    op.drop_column("news_items", "title_el_a2")
    # ### end Alembic commands ###
