"""add_variant_key_to_card_records

Revision ID: e77062d7fecd
Revises: 663bf29ea685
Create Date: 2026-02-07 19:25:00.976131+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e77062d7fecd"
down_revision: Union[str, Sequence[str], None] = "663bf29ea685"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("card_records", sa.Column("variant_key", sa.String(length=100), nullable=False))
    op.drop_constraint(op.f("uq_card_record_entry_type_tier"), "card_records", type_="unique")
    op.create_index("ix_card_records_variant_key", "card_records", ["variant_key"], unique=False)
    op.create_unique_constraint(
        "uq_card_record_entry_type_variant",
        "card_records",
        ["word_entry_id", "card_type", "variant_key"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_card_record_entry_type_variant", "card_records", type_="unique")
    op.drop_index("ix_card_records_variant_key", table_name="card_records")
    op.create_unique_constraint(
        op.f("uq_card_record_entry_type_tier"),
        "card_records",
        ["word_entry_id", "card_type", "tier"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("card_records", "variant_key")
    # ### end Alembic commands ###
