"""add_culture_question_generation_support

Revision ID: 78f11edc75df
Revises: 3b2f0360881c
Create Date: 2026-01-24 07:31:46.978234+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78f11edc75df"
down_revision: Union[str, Sequence[str], None] = "3b2f0360881c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_generation_logs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column(
            "source_fetch_history_id",
            sa.Uuid(),
            nullable=True,
            comment="Reference to the fetch history entry",
        ),
        sa.Column(
            "article_url",
            sa.String(length=500),
            nullable=False,
            comment="URL of the article used for generation",
        ),
        sa.Column(
            "article_title", sa.String(length=500), nullable=False, comment="Title of the article"
        ),
        sa.Column("status", sa.String(length=20), nullable=False, comment="'success' or 'failed'"),
        sa.Column(
            "question_id",
            sa.Uuid(),
            nullable=True,
            comment="Reference to generated question (if successful)",
        ),
        sa.Column(
            "error_message", sa.Text(), nullable=True, comment="Error details if generation failed"
        ),
        sa.Column(
            "tokens_used",
            sa.Integer(),
            nullable=True,
            comment="Total tokens consumed for generation",
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.ForeignKeyConstraint(["question_id"], ["culture_questions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["source_fetch_history_id"], ["source_fetch_history.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_generation_logs_article_url"),
        "question_generation_logs",
        ["article_url"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_generation_logs_question_id"),
        "question_generation_logs",
        ["question_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_generation_logs_source_fetch_history_id"),
        "question_generation_logs",
        ["source_fetch_history_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_generation_logs_status"),
        "question_generation_logs",
        ["status"],
        unique=False,
    )
    op.add_column(
        "culture_questions",
        sa.Column(
            "is_pending_review",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="True for AI-generated questions awaiting admin review",
        ),
    )
    op.add_column(
        "culture_questions",
        sa.Column(
            "source_article_url",
            sa.String(length=500),
            nullable=True,
            comment="URL of the source article used to generate this question",
        ),
    )
    op.alter_column("culture_questions", "deck_id", existing_type=sa.UUID(), nullable=True)
    op.create_index(
        op.f("ix_culture_questions_is_pending_review"),
        "culture_questions",
        ["is_pending_review"],
        unique=False,
    )
    op.create_index(
        op.f("ix_culture_questions_source_article_url"),
        "culture_questions",
        ["source_article_url"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_culture_questions_source_article_url"), table_name="culture_questions")
    op.drop_index(op.f("ix_culture_questions_is_pending_review"), table_name="culture_questions")
    op.alter_column("culture_questions", "deck_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("culture_questions", "source_article_url")
    op.drop_column("culture_questions", "is_pending_review")
    op.drop_index(op.f("ix_question_generation_logs_status"), table_name="question_generation_logs")
    op.drop_index(
        op.f("ix_question_generation_logs_source_fetch_history_id"),
        table_name="question_generation_logs",
    )
    op.drop_index(
        op.f("ix_question_generation_logs_question_id"), table_name="question_generation_logs"
    )
    op.drop_index(
        op.f("ix_question_generation_logs_article_url"), table_name="question_generation_logs"
    )
    op.drop_table("question_generation_logs")
    # ### end Alembic commands ###
