"""add tour_completed_at to user_settings

Revision ID: 51b4b6100fa3
Revises: bbfda52f7a72
Create Date: 2026-03-03 16:29:51.590641+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "51b4b6100fa3"
down_revision: Union[str, Sequence[str], None] = "bbfda52f7a72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_settings",
        sa.Column(
            "tour_completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the user completed the onboarding tour",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_settings", "tour_completed_at")
    # ### end Alembic commands ###
