"""update_word_entries_examples_comment

Revision ID: 41e6707eccbd
Revises: e77062d7fecd
Create Date: 2026-02-07 20:18:50.856605+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41e6707eccbd"
down_revision: Union[str, Sequence[str], None] = "e77062d7fecd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "word_entries",
        "examples",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="Usage examples: [{id?, greek, english, russian?, context?}, ...]",
        existing_comment="Usage examples: [{greek, english, russian?, context?}, ...]",
        existing_nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "word_entries",
        "examples",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="Usage examples: [{greek, english, russian?, context?}, ...]",
        existing_comment="Usage examples: [{id?, greek, english, russian?, context?}, ...]",
        existing_nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    # ### end Alembic commands ###
