"""drop cefr_level from word_entries

Revision ID: 5852b50707a2
Revises: 41e6707eccbd
Create Date: 2026-02-08 17:43:05.380758+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5852b50707a2"
down_revision: Union[str, Sequence[str], None] = "41e6707eccbd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_word_entries_cefr_level"), table_name="word_entries")
    op.drop_column("word_entries", "cefr_level")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "word_entries",
        sa.Column(
            "cefr_level",
            postgresql.ENUM("A1", "A2", "B1", "B2", "C1", "C2", name="decklevel"),
            autoincrement=False,
            nullable=True,
            comment="CEFR level (A1-C2), overrides deck level if set",
        ),
    )
    op.create_index(
        op.f("ix_word_entries_cefr_level"), "word_entries", ["cefr_level"], unique=False
    )
    # ### end Alembic commands ###
