"""add_analysis_fields_to_source_fetch_history

Revision ID: 2f4a31fe7bbd
Revises: 910421a50d22
Create Date: 2026-01-23 14:14:09.378404+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f4a31fe7bbd"
down_revision: Union[str, Sequence[str], None] = "910421a50d22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "source_fetch_history",
        sa.Column(
            "analysis_status",
            sa.String(length=20),
            nullable=True,
            comment="Analysis status: pending, completed, failed (null if not started)",
        ),
    )
    op.add_column(
        "source_fetch_history",
        sa.Column(
            "discovered_articles",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Array of discovered articles from AI analysis",
        ),
    )
    op.add_column(
        "source_fetch_history",
        sa.Column(
            "analysis_error", sa.Text(), nullable=True, comment="Error message if analysis failed"
        ),
    )
    op.add_column(
        "source_fetch_history",
        sa.Column(
            "analysis_tokens_used",
            sa.Integer(),
            nullable=True,
            comment="Number of API tokens consumed during analysis",
        ),
    )
    op.add_column(
        "source_fetch_history",
        sa.Column(
            "analyzed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when analysis completed",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source_fetch_history", "analyzed_at")
    op.drop_column("source_fetch_history", "analysis_tokens_used")
    op.drop_column("source_fetch_history", "analysis_error")
    op.drop_column("source_fetch_history", "discovered_articles")
    op.drop_column("source_fetch_history", "analysis_status")
    # ### end Alembic commands ###
