"""add_news_sources_table

Revision ID: 29695fa3f73f
Revises: 7b0abae73df7
Create Date: 2026-01-21 15:43:01.475066+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29695fa3f73f"
down_revision: Union[str, Sequence[str], None] = "7b0abae73df7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "news_sources",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column(
            "name", sa.String(length=255), nullable=False, comment="Display name for the source"
        ),
        sa.Column(
            "url",
            sa.String(length=500),
            nullable=False,
            comment="Base URL of the news source (must be unique)",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether source is used for question generation",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_news_sources_is_active"), "news_sources", ["is_active"], unique=False)
    op.create_index(op.f("ix_news_sources_url"), "news_sources", ["url"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_news_sources_url"), table_name="news_sources")
    op.drop_index(op.f("ix_news_sources_is_active"), table_name="news_sources")
    op.drop_table("news_sources")
    # ### end Alembic commands ###
