"""add_grammar_jsonb_fields_to_cards

Revision ID: a90d6c7deeb3
Revises: 83d73d26f04d
Create Date: 2026-01-29 12:58:25.193410+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a90d6c7deeb3"
down_revision: Union[str, Sequence[str], None] = "83d73d26f04d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cards",
        sa.Column(
            "noun_data", sa.JSON(), nullable=True, comment="Noun grammar: gender + 8 case forms"
        ),
    )
    op.add_column(
        "cards",
        sa.Column(
            "verb_data",
            sa.JSON(),
            nullable=True,
            comment="Verb grammar: voice + 30 conjugations + 2 imperative",
        ),
    )
    op.add_column(
        "cards",
        sa.Column(
            "adjective_data",
            sa.JSON(),
            nullable=True,
            comment="Adjective grammar: 24 declensions + 2 comparison forms",
        ),
    )
    op.add_column(
        "cards",
        sa.Column(
            "adverb_data",
            sa.JSON(),
            nullable=True,
            comment="Adverb grammar: comparative + superlative",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cards", "adverb_data")
    op.drop_column("cards", "adjective_data")
    op.drop_column("cards", "verb_data")
    op.drop_column("cards", "noun_data")
    # ### end Alembic commands ###
