"""add_avatar_url_to_users

Revision ID: 037928b86d1e
Revises: 76173e4f6948
Create Date: 2026-01-20 13:55:12.351854+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "037928b86d1e"
down_revision: Union[str, Sequence[str], None] = "76173e4f6948"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "avatar_url",
            sa.String(length=500),
            nullable=True,
            comment="S3 key for user avatar (e.g., avatars/{user_id}/{uuid}.jpg)",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "avatar_url")
    # ### end Alembic commands ###
