"""remove notified field from user_achievements

Revision ID: 76173e4f6948
Revises: 7b7663a8d448
Create Date: 2026-01-18 14:22:56.025816+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76173e4f6948"
down_revision: Union[str, Sequence[str], None] = "7b7663a8d448"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_achievements", "notified")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_achievements",
        sa.Column(
            "notified", sa.BOOLEAN(), autoincrement=False, nullable=False, server_default="false"
        ),
    )
    # ### end Alembic commands ###
