"""add auth0_id to users

Revision ID: 1aef63b5f6f5
Revises: 78dff0112c97
Create Date: 2026-01-08 17:05:33.641663+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aef63b5f6f5'
down_revision: Union[str, Sequence[str], None] = '78dff0112c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth0_id', sa.String(length=255), nullable=True, comment='Auth0 user identifier (sub claim)'))
    op.create_index(op.f('ix_users_auth0_id'), 'users', ['auth0_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_auth0_id'), table_name='users')
    op.drop_column('users', 'auth0_id')
    # ### end Alembic commands ###
