import type { User } from '@/types/auth';

export const mockUsers: Array<User & { password: string }> = [
  {
    id: 'user-1',
    email: 'demo@learngreekeasy.com',
    password: 'Demo123!',
    name: 'Demo User',
    role: 'premium',
    avatar: undefined,
    preferences: {
      language: 'en',
      dailyGoal: 15,
      notifications: true,
    },
    stats: {
      streak: 7,
      wordsLearned: 142,
      totalXP: 1250,
      lastActivity: new Date('2025-10-27'),
      joinedDate: new Date('2025-10-01'),
    },
    createdAt: new Date('2025-10-01'),
    updatedAt: new Date('2025-10-27'),
  },
  {
    id: 'user-2',
    email: 'admin@learngreekeasy.com',
    password: 'Admin123!',
    name: 'Admin User',
    role: 'admin',
    avatar: undefined,
    preferences: {
      language: 'en',
      dailyGoal: 30,
      notifications: true,
    },
    stats: {
      streak: 15,
      wordsLearned: 500,
      totalXP: 5000,
      lastActivity: new Date('2025-10-28'),
      joinedDate: new Date('2025-09-01'),
    },
    createdAt: new Date('2025-09-01'),
    updatedAt: new Date('2025-10-28'),
  },
  {
    id: 'user-3',
    email: 'free@learngreekeasy.com',
    password: 'Free123!',
    name: 'Free User',
    role: 'free',
    avatar: undefined,
    preferences: {
      language: 'en',
      dailyGoal: 10,
      notifications: false,
    },
    stats: {
      streak: 0,
      wordsLearned: 25,
      totalXP: 100,
      lastActivity: new Date('2025-10-25'),
      joinedDate: new Date('2025-10-20'),
    },
    createdAt: new Date('2025-10-20'),
    updatedAt: new Date('2025-10-25'),
  },
];
