"""One-shot bucket-wide WebP derivative backfill script (PERF-11).

Iterates every original image object in the configured S3 bucket, downloads its
bytes, and generates WebP derivatives using the same pipeline introduced by
PERF-10 (``S3Service.generate_image_derivatives`` via ``s3_service.py``).

Objects that pre-date PERF-10 were uploaded without WebP derivatives and therefore
cannot benefit from the ``srcset`` the frontend generates.  This script back-fills
them idempotently: derivative keys that already exist are skipped (HEAD check per
width before any write), so re-runs are safe.

For the Cache-Control raise (PERF-01, 1-year immutable), re-run the companion
script ``backfill_s3_cache_control.py`` — it already reads ``_DEFAULT_CACHE_CONTROL``
from ``s3_service.py``, so no code change is needed there.

Derivative key scheme (contractual — mirrors PERF-10):
    ``<base_s3_key_without_ext>_<width>w.webp``
    e.g.  situation-pictures/abc123/sha256hash_400w.webp

Usage:
    # Dry-run first — no writes, logs what would be generated
    railway run python -m src.scripts.backfill_image_derivatives --dry-run

    # Live run — generates and uploads missing WebP derivatives
    railway run python -m src.scripts.backfill_image_derivatives

Run MANUALLY from within the Railway environment after PERF-10 deploys.
NOT wired into the automated deploy pipeline / no GHA / no Dockerfile CMD.

Notes:
    - Idempotent: re-running skips derivative keys that already exist.
    - Per-object error isolation: one bad key is logged and counted but does
      not abort the whole run (intentional deviation from load_translations_kaikki
      which calls sys.exit on first error).
    - Objects whose key ends with ``_<width>w.webp`` are skipped automatically so
      we never attempt to derive derivatives from derivatives.
    - Non-image content types (audio, etc.) are detected via HEAD and skipped.
"""

import argparse
import posixpath
import re
import sys
from dataclasses import dataclass
from typing import Any

from botocore.exceptions import BotoCoreError, ClientError
from loguru import logger

from src.config import settings
from src.services.s3_service import _IMAGE_CONTENT_TYPES, DERIVATIVE_WIDTHS, get_s3_service

# Regex that matches derivative keys generated by PERF-10/PERF-11 so we never
# attempt to build second-generation derivatives.
# Pattern: any key ending with  _<digits>w.webp
_DERIVATIVE_KEY_RE = re.compile(r"_\d+w\.webp$")


@dataclass
class _Counters:
    """Mutable counters accumulated across all objects in the backfill run."""

    scanned: int = 0
    generated: int = 0
    skipped_derivative: int = 0
    skipped_non_image: int = 0
    skipped_exists: int = 0
    errors: int = 0


def _is_derivative_key(key: str) -> bool:
    """Return True if *key* looks like a PERF-10/PERF-11 derivative."""
    return bool(_DERIVATIVE_KEY_RE.search(key))


def _derivative_exists(client: Any, bucket: str, derivative_key: str) -> bool:
    """Return True if *derivative_key* already exists in S3 (HEAD request)."""
    try:
        client.head_object(Bucket=bucket, Key=derivative_key)
        return True
    except ClientError as exc:
        if exc.response.get("Error", {}).get("Code") == "404":
            return False
        raise  # unexpected error — let caller handle
    except BotoCoreError:
        return False


def _plan_dry_run(client: Any, bucket: str, key: str, counters: _Counters) -> None:
    """Log planned derivative keys for *key* without writing (dry-run path)."""
    head = client.head_object(Bucket=bucket, Key=key)
    content_type = head.get("ContentType", "")
    if content_type not in _IMAGE_CONTENT_TYPES:
        logger.debug(f"Skipping {key!r} — non-image content_type={content_type!r}")
        counters.skipped_non_image += 1
        return
    base_without_ext = posixpath.splitext(key)[0]
    for width in DERIVATIVE_WIDTHS:
        derivative_key = f"{base_without_ext}_{width}w.webp"
        logger.info(f"[DRY RUN] {key!r} -> would generate {derivative_key!r}")
        counters.generated += 1


def _process_live(
    client: Any,
    bucket: str,
    key: str,
    service: Any,
    counters: _Counters,
) -> None:
    """Generate and upload missing WebP derivatives for *key* (live path)."""
    head = client.head_object(Bucket=bucket, Key=key)
    content_type = head.get("ContentType", "")
    if content_type not in _IMAGE_CONTENT_TYPES:
        logger.debug(f"Skipping {key!r} — non-image content_type={content_type!r}")
        counters.skipped_non_image += 1
        return

    base_without_ext = posixpath.splitext(key)[0]
    widths_to_generate: list[int] = []
    for width in DERIVATIVE_WIDTHS:
        derivative_key = f"{base_without_ext}_{width}w.webp"
        if _derivative_exists(client, bucket, derivative_key):
            logger.debug(f"Skipping {derivative_key!r} — already exists")
            counters.skipped_exists += 1
        else:
            widths_to_generate.append(width)

    if not widths_to_generate:
        return  # all derivatives already present

    response = client.get_object(Bucket=bucket, Key=key)
    image_bytes: bytes = response["Body"].read()

    uploaded_keys = service.generate_image_derivatives(
        key, image_bytes, widths=tuple(widths_to_generate)
    )
    counters.generated += len(uploaded_keys)
    missed = len(widths_to_generate) - len(uploaded_keys)
    if missed:
        logger.warning(f"{key!r}: {missed} derivative(s) failed to generate/upload")


def _process_bucket(
    client: Any,
    bucket: str,
    service: Any,
    dry_run: bool,
    counters: _Counters,
) -> None:
    """Paginate through every object in the bucket and dispatch to the right handler.

    Isolated so that ``backfill`` stays below the complexity threshold.
    Per-object errors are caught and counted here; the loop always continues.
    """
    paginator = client.get_paginator("list_objects_v2")
    for page in paginator.paginate(Bucket=bucket):
        for obj in page.get("Contents", []):  # guard: empty pages have no Contents key
            key = obj["Key"]
            counters.scanned += 1

            if _is_derivative_key(key):
                counters.skipped_derivative += 1
                continue

            try:
                if dry_run:
                    _plan_dry_run(client, bucket, key, counters)
                else:
                    _process_live(client, bucket, key, service, counters)
            except Exception as exc:
                # Per-object isolation: one bad key must not abort a bucket-wide backfill.
                logger.warning(f"Error processing {key!r}: {exc}")
                counters.errors += 1


def backfill(dry_run: bool) -> None:
    """Scan every image object in the bucket and generate missing WebP derivatives.

    Args:
        dry_run: When True, log planned writes without calling S3.
    """
    service = get_s3_service()
    client = service._get_client()
    if client is None:
        logger.error("S3 not configured — aborting")
        sys.exit(1)

    bucket = settings.effective_s3_bucket_name
    if not bucket:
        logger.error("S3 bucket name not configured — aborting")
        sys.exit(1)

    mode_label = "DRY RUN" if dry_run else "LIVE"
    logger.info(f"Starting WebP derivative backfill [{mode_label}] on bucket: {bucket}")

    counters = _Counters()
    _process_bucket(client, bucket, service, dry_run, counters)

    action = "would generate" if dry_run else "generated"
    logger.info(
        f"Backfill complete [{mode_label}]: "
        f"scanned={counters.scanned:,} {action}={counters.generated:,} "
        f"skipped_derivative={counters.skipped_derivative:,} "
        f"skipped_non_image={counters.skipped_non_image:,} "
        f"skipped_exists={counters.skipped_exists:,} "
        f"errors={counters.errors:,}"
    )

    if counters.errors:
        logger.error(f"{counters.errors:,} object(s) failed — review warnings above")
        sys.exit(1)


def main() -> None:
    """Parse arguments and run WebP derivative backfill."""
    parser = argparse.ArgumentParser(
        description=(
            "Back-fill WebP derivatives for every original image in the configured S3 bucket. "
            "Run with --dry-run first to preview what would be generated. "
            "Idempotent: derivative keys that already exist are skipped. "
            "For the 1-year Cache-Control raise (PERF-01), also re-run "
            "backfill_s3_cache_control.py after this script completes."
        )
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        default=False,
        help="Log planned derivative keys without writing to S3 (default: live run)",
    )
    args = parser.parse_args()
    backfill(dry_run=args.dry_run)


if __name__ == "__main__":
    main()
